apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: dexmon
spec:
  type: ClusterIP
  ports:
    - port: 9042
      targetPort: 9042
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  namespace: dexmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:4.1
          ports:
            - containerPort: 9042
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: DexMonCluster




