apiVersion: v1
kind: Service
metadata:
  name: glucose-receiver
  namespace: dexmon
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: glucose-receiver
---
apiVersion: v1
kind: Service
metadata:
  name: glucose-processor
  namespace: dexmon
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: glucose-processor
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: dexmon
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: notification-service
---
apiVersion: v1
kind: Service
metadata:
  name: data-archival
  namespace: dexmon
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: data-archival
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: dexmon
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
  selector:
    app: api-gateway




