server:
  port: 8084

spring:
  application:
    name: data-archival
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dexmon}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

archival:
  s3:
    bucket: ${S3_BUCKET:dexmon-archive}
    prefix: ${S3_PREFIX:glucose/}





