server:
  port: 8081

spring:
  application:
    name: glucose-receiver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

kafka:
  bootstrap-servers: ${spring.kafka.bootstrap-servers}





