server:
  port: 8085

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dexmon}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    cassandra:
      contact-points: ${CASSANDRA_CONTACT_POINTS:localhost}
      port: ${CASSANDRA_PORT:9042}
      local-datacenter: ${CASSANDRA_DC:datacenter1}
      keyspace-name: dexmon_alerts

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"



