global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'glucose-services'
    static_configs:
      - targets:
          - 'host.docker.internal:8081'
          - 'host.docker.internal:8082'
          - 'host.docker.internal:8083'
          - 'host.docker.internal:8084'
          - 'host.docker.internal:8085'



