name: Build Architecture PDF

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install md-to-pdf
        run: |
          npm i -g md-to-pdf@5.2.4

      - name: Generate PDF
        run: |
          md-to-pdf docs/ARCHITECTURE.md --config-file <(echo '{"as_html": false,"stylesheet": ["https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown.min.css"],"pdf_options": {"format": "A4","margin": "20mm"}}') --output docs/ARCHITECTURE.pdf

      - name: Commit PDF
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add docs/ARCHITECTURE.pdf
          if git diff --cached --quiet; then
            echo "No PDF changes"; exit 0; fi
          git commit -m "docs: update architecture PDF"
          git push


